---
- hosts: all
  become: true
  vars:
    workspace: "{{ lookup('env','WORKSPACE') }}"
  vars_files: ["secrets/{{site_id}}","secrets/ssh_passwords"]
  tasks:
  - name: Create configuration.php
    template:
      src: "templates/id.conf.j2"
      dest: "{{ doc_root }}/.env"
      owner: "{{ server_runs_as }}"
      group: "{{ server_runs_as_group }}"

  - name: Create .htversion file
    file:
      path: "{{ doc_root }}/public/.htversion"
      state: touch
      owner: "{{ server_runs_as }}"
      group: "{{ server_runs_as_group }}"

  - name: Write commit number .htversion to file
    shell: echo "{{ lookup('env','BUILD_NUMBER') }}" > {{ doc_root }}/public/.htversion

  - name: Unarchive artifact on remote server
    become: true
    unarchive:
      src: "{{ workspace | default('') }}/{{ artifact_filename }}"
      dest: "{{ doc_root }}"
      copy: yes
      owner: "{{ server_runs_as }}"
      group: "{{ server_runs_as_group }}"
      
  - name: Create all cli cronjobs
    become: false
    tags: cron
    when: (deploy_env == "prod-id")
    cron:
      name: "{{item.name}}"
      minute: "*/1"
      job: "/usr/bin/php {{item.url}} &> /dev/null"
    with_items :
    - {
      name: "Cron for Scheduler run", 
      url: "{{ doc_root }}artisan schedule:run"
    }
